name: Build & Deploy BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"  # 每天凌晨 1:00 自动构建

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Obfuscator & Obfuscate File
        run: |
          npm install -g javascript-obfuscator
          wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/build/unobfuscated-worker.js
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --control-flow-flattening false \
            --dead-code-injection false \
            --identifier-names-generator hexadecimal \
            --rename-globals false \
            --string-array true \
            --string-array-encoding 'base64' \
            --string-array-threshold 0.5 \
            --unicode-escape-sequence false

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ':arrow_up: Update latest BPB panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

      - name: Publish to Cloudflare Workers
        run: |
          npm install -g wrangler
          wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}


